[package]
name = "meatbag-app-login"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
env_logger = "0.9.3"
futures = "0.3.25"
log = "0.4.17"
reqwest = { version = "0.11.13", features = ["json", "rustls", "rustls-tls"] }
serde = { version = "1.0.147", features = ["derive"] }
tokio = { version = "1.22.0", features = ["rt", "macros", "rt-multi-thread"] }
